### ISSUE TITLE
convert SimBERT Base to SavedModel for tensorflow/serving

### ISSUE THREAD

**Issue by zhnglicho** [ZhuiyiTechnology/pretrained-models#5]
I hope to load **SimBERT Base** using tensorflow/serving ,  anyone did this ? or  can you give me some advices ?

**Comment by zhnglicho** [comment]
## runtime enviroment:  tensorflow2.1 + bert4keras0.8.4
### please set TF_KERAS enviroment variable before run this script.   widnows: set TF_KERAS=1，  linux:  export TF_KERAS=1
```
import tensorflow as tf
from bert4keras.models import build_transformer_model

config_path = 'chinese_simbert_L-12_H-768_A-12\bert_config.json'
checkpoint_path = 'chinese_simbert_L-12_H-768_A-12\bert_model.ckpt'

bert = build_transformer_model(config_path,
                                   checkpoint_path,
                                   with_pool='linear',
                                   application='unilm',
                                   return_keras_model=False)

if __name__ == "__main__":
    model = tf.keras.models.Model(bert.model.inputs, bert.model.outputs)
    model.save("models\simbert")
```

**Comment by hlang8160** [comment]
这种情况貌似无法在tf1.14版本中import，会缺少相关算子，请问大佬是如何解决的？tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'Einsum' in binary running on MacBook-Pro.local. 
Make sure the Op and Kernel are registered in the binary running in this process. 
Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.)
 `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

**Comment by hurun** [comment]
> 这种情况貌似无法在tf1.14版本中import，会缺少相关算子，请问大佬是如何解决的？tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'Einsum' in binary running on MacBook-Pro.local. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

使用tf2版本，建议tf=2.2.0， 修改代码如下
with tf.compat.v1.Session(graph=tf.Graph()) as sess:
    tf.compat.v1.saved_model.loader.load(sess, ["serve"], "./tfserving_models/0")
    graph = tf.compat.v1.get_default_graph()
