### ISSUE TITLE
一人血书求作者接入Huggingface

### ISSUE THREAD

**Issue by wmathor** [ZhuiyiTechnology/pretrained-models#6]

**Comment by bojone** [comment]
作者表示对Huggingface不熟悉也不喜欢，实在做不到啊（公司内部也没几个人用Huggingface的）

**Comment by shiwl0329** [comment]
> 作者表示对Huggingface不熟悉也不喜欢，实在做不到啊（公司内部也没几个人用Huggingface的）

用huggingface很方便
